language: node.js
sudo: required
node_js:
- 11.6.0
cache: npm
before_install:
- chmod +x ecr_credentials.sh
- "./ecr_credentials.sh"
- curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
- unzip awscliv2.zip
- sudo ./aws/install
- aws2 ec2 describe-instances --profile amplifyProfile
- amplify pull --appId d2fuhdsnl72e9r --envName dev
#- export AWS_PROFILE=amplifyProfile
install:
- npm install
- npm install -g @aws-amplify/cli
- amplify pull
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: testapp221307-dev
  acl: public_read
  on:
    repo: duranzavala/react-test-app
    branch: feature/architecture
