language: node.js
node_js:
  - 11.6.0
cache: npm

install:
  - npm install

script:
  - amplifyPush --simple
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master